def check(s):
    input(f"\n{s} ...... ")
    print("done")

while True:
    print()
    print()
    print("------------------------")
    print("------ NEW MODULE ------")
    print("------------------------")
    check("Press Enter to continue")
    print()
    check("Change export default")
    check("Add 'shortCode' property")
    check("Add 'nuclei' property")
    check("Change phases ph1 and ph2")
    check("Change other phases")
    check("Define gradient list")
    check("Change gradients")
    check("Change go to goscnp (1H modules)")
    check("Delete things at the end")
