name: publish-website
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: Perform hard reset to master branch
      run: |
        git fetch origin master --tags
        git reset --hard origin/master

    - name: Setup node.js v14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Compile TypeScript code
      run: |
        npm install typescript
        tsc

    - name: Run tests with Mocha
      run: |
        npm install mocha
        npm test

    - name: Build old versions of website
      run: |
        ./create_old_versions.sh

    - name: Push content to gh-pages branch
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "<>"
        git add -A
        git add -f build/    # Need -f because build/ is gitignored.
        git add -f */*/*/build/
        git commit -m "Update published website" || true
        git push -f
